 <footer class="index-footer">
        <article class="index-footer-description">
            <section class="index-footer__menu">
                <h3>Menu</h3>
                <ul class="menu-list">
                    <li class="menu-list__item"><a href="index.php">Home</a></li>
                    <li class="menu-list__item"><a href="jobs.php">Jobs</a></li>
                    <li class="menu-list__item"><a href="apply.php">Apply</a></li>
                    <li class="menu-list__item"><a href="about.php">About</a></li>
                    <li class="menu-list__item"><a href="enhancement.php">Enhancement</a></li>
                </ul>
            </section>

            <section class="index-footer__address">
                <h3>Address</h3>
                <p class="address">Jalan 15/8, SS15, Subang Jaya, Selengor</p>
                <p class="phone-no">+60123456789</p>
                <a href="mailto:into@byteme.net"><p class="mail-address">Contact Us</p></a>
            </section>

            <section class="index-footer__social-link">
                    <h3>Social Links</h3>
                    <div class="social-media-links">
                        <a href="https://facebook.com"><img src="images/facebook.png" alt="Facebook"></a>
                        <a href="https://linkedin.com"><img src="images/linkedin.png" alt="Linkedin"></a>
                        <a href="https://telegram.com"><img src="images/telegram.png" alt="Telegram"></a>
                        <a href="https://twitter.com"><img src="images/twitter.png" alt="X"></a> 
                    </div>
          </section>
        </article>

        <hr>

        <h4 class="index-footer__copy-right">&copy; All Rights Reserved. By ByteMe.</h4>
   </footer>