<nav>
            <ul class="navbar-list">
                <li class="navbar-list__item active" >
                    <a href="index.php" class="navbar-list__link ">
                        Home
                    </a>
                </li>

                <li class="navbar-list__item ">
                    <a href="jobs.php" class="navbar-list__link">
                        Jobs
                    </a>
                </li>

                <li class="navbar-list__item">
                    <a href="apply.php" class="navbar-list__link">
                        Apply
                    </a>
                </li>

                <li class="navbar-list__item">
                    <a href="about.php" class="navbar-list__link">
                        About
                    </a>
                </li>

                <li class="navbar-list__item">
                    <a href="enhancement.php" class="navbar-list__link">
                        Enhancement
                    </a>
                </li>
            </ul> 
        </nav>